name: Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Clone the repository on the runner
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'

    - name: Clean install NPM modules
      run: npm ci

    - name: Install Playwright browser binaries
      run: npx playwright install

    - name: Start server
      run: npm run server &

    - name: Start front-end
      run: npm run start &

    - name: Run tests
      run: npm run test

  # deploy_server:
  #   runs-on: ubuntu-latest
  #   needs: build_and_test

  #   steps:
  #   - name: Clone the GitHub repository on the runner
  #     uses: actions/checkout@v4
    
  #   - name: Deploy server to Render
  #     uses: JorgeLNJunior/render-deploy@v1.4.5
  #     with:
  #       service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
  #       api_key: ${{ secrets.MY_RENDER_API_KEY }}
  #       wait_deploy: true
