# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - name: Clone the repository on the runner
      uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Clean install the defined dependencies
      run: npm ci

    - name: Install Playwright browser binaries
      run: npx playwright install

    - name: Start server and front-end
      run: |
        npm run server &
        npm run start &
        sleep 20

    - name: Run tests
      run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Clone the GitHub repository on the runner
      uses: actions/checkout@v4
    
    - name: Deploy server to Render
      uses: JorgeLNJunior/render-deploy@v1.4.5
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
        wait_deploy: true